#pragma once
//
// AffineUI — tiny GPU-accelerated HTML5/CSS UI renderer.
//
// Usage at its simplest:
//
//     #include "affineui.h"
//     int main() { return affineui::run("<h1>Hello, world!</h1>"); }
//
// `run()` is the canonical entry point and handles window creation,
// GPU init, event loop, default styling, default font, and shutdown.
// Drop down to affineui::App / affineui::Document for fine control.
//
// Distribution forms:
//   - This modular include tree (development / advanced embedders)
//   - Two-file release  (`affineui.h` + `affineui.cpp`) generated by
//     tools/amalgamate.py. End-users copy those two files into their
//     project and they're done.
//

#include "affineui/app.h"
#include "affineui/document.h"
#include "affineui/painter.h"
#include "affineui/renderer.h"
#include "affineui/themes.h"
#include "affineui/types.h"
#include "affineui/ui.h"
#include "affineui/version.h"

#ifndef AFFINEUI_NO_IMM
#    include "affineui/imm.h"
#endif

// Windowing-toolkit adapters — opt-in via macros. Each pulls in the
// toolkit's headers and adds free functions in `affineui::sokol` /
// `affineui::sdl` that translate events, query viewport, set cursor,
// and (optionally) wire callbacks. Define the corresponding macro
// *before* including this header.
#if defined(AFFINEUI_WITH_SOKOL)
#    include "affineui/sokol.h"
#endif
#if defined(AFFINEUI_WITH_SDL)
#    include "affineui/sdl.h"
#endif

namespace affineui {

/// Run a retained-mode document. The simplest possible entry point.
/// Returns the OS exit code.
int run(std::string_view html);

/// Run an imm-mode application. The view function is invoked when
/// AffineUI knows the UI definition could have changed; painting runs
/// every frame off the retained DOM regardless.
int run(std::function<void()> view_fn);

/// Run with explicit config. Fields default to values that produce a
/// usable app — override only what you care about.
int run(App::Config cfg);

/// Run with explicit config + imm view function.
int run(App::Config cfg, std::function<void()> view_fn);

}  // namespace affineui
