// ImmRuntime — per-Document immediate-mode reconciler. Phase 3A:
// "dumb reconcile" (set-until-mismatch). For each open_element /
// text call we walk a cursor through the existing DOM under the
// current parent; matches (same id + same tag, or same node type
// for text) reuse the existing node in place. Mismatches destroy
// from the cursor onwards and re-insert. Text-only changes never
// touch the DOM structure — they update the node's text content
// in place. State slots and click handlers stay tied to nodes
// across renders because the nodes themselves stay.

#include "imm/imm_runtime.h"

#include "affineui/document.h"

#include <cstdio>
#include <cstring>

#if !defined(AFFINEUI_STUB_BUILD)
#    include <lexbor/dom/dom.h>
#    include <lexbor/html/html.h>
#endif

namespace affineui::detail {

ImmRuntime*& imm_active_runtime() {
    thread_local ImmRuntime* tls = nullptr;
    return tls;
}

ImmRuntime::ImmRuntime()  = default;
ImmRuntime::~ImmRuntime() {
    // Free any state slots we own. The user's T destructors run via
    // the stored function pointer.
    for (auto& [key, slot] : state_slots_) {
        if (slot.data) {
            if (slot.dtor) slot.dtor(slot.data);
            ::operator delete(slot.data);
        }
    }
}

void ImmRuntime::bind(Document* owner, lxb_html_document_t* doc) {
    owner_ = owner;
    doc_   = doc;
}

void ImmRuntime::set_view_fn(std::function<void()> fn) {
    view_fn_ = std::move(fn);
    dirty_   = true;   // first paint needs to run the fresh view fn
}

#if defined(AFFINEUI_STUB_BUILD)

void ImmRuntime::run_view_fn() {}
void* ImmRuntime::get_or_create_slot(std::uint64_t, std::size_t size, std::size_t,
                                     void (*ctor)(void*), void (*dtor)(void*)) {
    (void)dtor;
    void* p = ::operator new(size);
    ctor(p);
    return p;
}
void ImmRuntime::register_click(std::uint64_t, std::function<void()>) {}
bool ImmRuntime::invoke_click(std::string_view) { return false; }
lxb_dom_element_t* ImmRuntime::open_element(std::string_view, std::uint64_t, std::string_view) { return nullptr; }
void ImmRuntime::close_element() {}
void ImmRuntime::set_class(lxb_dom_element_t*, std::string_view) {}
void ImmRuntime::set_attr(lxb_dom_element_t*, std::string_view, std::string_view) {}
void ImmRuntime::append_text_to_current(std::string_view) {}

#else  // !AFFINEUI_STUB_BUILD

namespace {

inline const lxb_char_t* as_lxb(const char* p) {
    return reinterpret_cast<const lxb_char_t*>(p);
}
inline const lxb_char_t* as_lxb(std::string_view s) {
    return reinterpret_cast<const lxb_char_t*>(s.data());
}

// Render a hex-encoded 64-bit hash for use in element ids. Returns
// "aui-imm-{16-hex-chars}", deterministic per call-site.
std::string format_imm_id(std::uint64_t hash) {
    char buf[32];
    std::snprintf(buf, sizeof(buf), "aui-imm-%016llx",
                  static_cast<unsigned long long>(hash));
    return std::string(buf);
}

// Destroy `start` and every node following it as a sibling, inclusive.
// Lexbor's CSS mutation hooks are fragile for cascade-attached
// elements (see Known Issues in docs/ROADMAP.md), so the hooks are
// temporarily nulled out for the destroy walk; the document's
// stylesheet state stays attached for the new tree and the orphaned
// cascade entries get reclaimed when the document itself is
// destroyed. Safe because we don't reuse any of the destroyed nodes.
void destroy_from(lxb_dom_node_t* start) {
    if (!start) return;
    auto* doc = start->owner_document;
    auto* prev_remove  = doc ? doc->ev_remove  : nullptr;
    auto* prev_destroy = doc ? doc->ev_destroy : nullptr;
    if (doc) {
        doc->ev_remove  = nullptr;
        doc->ev_destroy = nullptr;
    }
    auto* cur = start;
    while (cur) {
        auto* next = cur->next;
        lxb_dom_node_destroy_deep(cur);
        cur = next;
    }
    if (doc) {
        doc->ev_remove  = prev_remove;
        doc->ev_destroy = prev_destroy;
    }
}

// True when `cursor` is an element whose tag matches `tag` AND whose
// `id` attribute equals `id_str`. Used for cursor-vs-incoming match
// in open_element. We match on the autogenerated `aui-imm-{hash}` id
// — the call-site hash uniquely identifies a logical element across
// renders, so id equality means "this is the same logical element."
bool element_matches(lxb_dom_node_t* cursor,
                     std::string_view tag,
                     std::string_view id_str) {
    if (!cursor || cursor->type != LXB_DOM_NODE_TYPE_ELEMENT) return false;
    auto* el = lxb_dom_interface_element(cursor);
    std::size_t nlen = 0;
    const auto* name = lxb_dom_element_qualified_name(el, &nlen);
    if (!name || nlen != tag.size() ||
        std::memcmp(name, tag.data(), tag.size()) != 0) return false;
    std::size_t idlen = 0;
    const auto* id_attr = lxb_dom_element_get_attribute(
        el,
        reinterpret_cast<const lxb_char_t*>("id"), 2,
        &idlen);
    return id_attr && idlen == id_str.size() &&
           std::memcmp(id_attr, id_str.data(), id_str.size()) == 0;
}

}  // namespace

void ImmRuntime::run_view_fn() {
    if (!view_fn_ || !doc_) return;

    auto* body = lxb_dom_interface_node(
        lxb_html_document_body_element(doc_));
    if (!body) return;

    // Click handlers are rebuilt on every render — the view fn calls
    // on_click on every Scope it opens, so we want a clean map each
    // pass. State slots persist (keyed by call-site hash).
    click_handlers_.clear();

    parent_stack_.clear();
    cursor_stack_.clear();
    parent_stack_.push_back(body);
    cursor_stack_.push_back(lxb_dom_node_first_child(body));

    auto*& tls = imm_active_runtime();
    auto*  prev = tls;
    tls = this;

    view_fn_();

    tls = prev;

    // Kill any tail under body that this render didn't visit. Same
    // logic close_element runs at every level — this catches the
    // outermost level (body's leftover children).
    destroy_from(cursor_stack_.back());

    parent_stack_.clear();
    cursor_stack_.clear();
    dirty_ = false;
}

void* ImmRuntime::get_or_create_slot(std::uint64_t key,
                                     std::size_t   size,
                                     std::size_t   /*align*/,
                                     void (*ctor)(void*),
                                     void (*dtor)(void*)) {
    auto it = state_slots_.find(key);
    if (it != state_slots_.end()) return it->second.data;
    void* p = ::operator new(size);
    if (ctor) ctor(p);
    state_slots_.emplace(key, ImmStateSlot{p, size, dtor});
    return p;
}

void ImmRuntime::register_click(std::uint64_t scope_hash,
                                std::function<void()> cb) {
    click_handlers_[scope_hash] = std::move(cb);
}

bool ImmRuntime::invoke_click(std::string_view elem_id) {
    // Element ids look like "aui-imm-{16-hex}". Parse the hex back
    // into the scope hash and look up.
    constexpr std::string_view prefix = "aui-imm-";
    if (elem_id.size() != prefix.size() + 16) return false;
    if (elem_id.substr(0, prefix.size()) != prefix) return false;
    std::uint64_t hash = 0;
    for (std::size_t i = 0; i < 16; ++i) {
        const char c = elem_id[prefix.size() + i];
        std::uint64_t v;
        if      (c >= '0' && c <= '9') v = static_cast<std::uint64_t>(c - '0');
        else if (c >= 'a' && c <= 'f') v = static_cast<std::uint64_t>(10 + c - 'a');
        else return false;
        hash = (hash << 4) | v;
    }
    auto it = click_handlers_.find(hash);
    if (it == click_handlers_.end()) return false;
    // Bind the active-runtime TLS while the handler runs so
    // `mark_state_mutated` calls from within `use_state` references
    // find us.
    auto*& tls  = imm_active_runtime();
    auto*  prev = tls;
    tls = this;
    it->second();
    tls = prev;
    // Pessimistically mark dirty after any click handler (Phase 3
    // upgrades to per-state-slot tracking).
    dirty_ = true;
    return true;
}

lxb_dom_element_t* ImmRuntime::open_element(std::string_view tag,
                                            std::uint64_t scope_hash,
                                            std::string_view classes) {
    if (parent_stack_.empty() || !doc_) return nullptr;
    auto* parent = parent_stack_.back();
    auto& parent_cursor = cursor_stack_.back();

    const auto id_str = format_imm_id(scope_hash);

    // Reuse path: cursor element matches what the view fn is asking
    // for. No DOM mutation, no cascade re-run, just walk forward.
    if (element_matches(parent_cursor, tag, id_str)) {
        auto* reused = lxb_dom_interface_element(parent_cursor);
        // Class might have changed across renders (the call site
        // produces a different `classes` arg).
        if (!classes.empty()) {
            std::size_t cur_len = 0;
            const auto* cur_class = lxb_dom_element_get_attribute(
                reused,
                reinterpret_cast<const lxb_char_t*>("class"), 5,
                &cur_len);
            const bool same = cur_class && cur_len == classes.size() &&
                std::memcmp(cur_class, classes.data(), classes.size()) == 0;
            if (!same) {
                lxb_dom_element_set_attribute(
                    reused,
                    reinterpret_cast<const lxb_char_t*>("class"), 5,
                    as_lxb(classes), classes.size());
            }
        } else {
            // View fn passed no class this round; strip any old one.
            lxb_dom_element_remove_attribute(
                reused,
                reinterpret_cast<const lxb_char_t*>("class"), 5);
        }
        // Advance parent's cursor past the reused element, then
        // descend: this element becomes the new top of the parent
        // stack and its first_child becomes the cursor for its
        // children.
        auto* reused_node = lxb_dom_interface_node(reused);
        parent_cursor = reused_node->next;
        parent_stack_.push_back(reused_node);
        cursor_stack_.push_back(lxb_dom_node_first_child(reused_node));
        return reused;
    }

    // Mismatch: anything still living from parent_cursor onward is
    // stale (different tag, different scope hash, different node
    // type, or just no more old children). Destroy it and append a
    // fresh element.
    destroy_from(parent_cursor);
    parent_cursor = nullptr;

    auto* elem = lxb_dom_document_create_element(
        lxb_dom_interface_document(doc_),
        as_lxb(tag), tag.size(),
        nullptr);
    if (!elem) {
        parent_stack_.push_back(parent);  // keep stacks balanced
        cursor_stack_.push_back(nullptr);
        return nullptr;
    }

    // Set id + class BEFORE insert so lexbor's ev_insert cascade
    // sees them and matches `.cls` / `#id` selectors on first
    // attach. See lexbor's examples/lexbor/styles/events_insert.c.
    lxb_dom_element_set_attribute(
        elem,
        reinterpret_cast<const lxb_char_t*>("id"), 2,
        as_lxb(id_str.c_str()), id_str.size());
    if (!classes.empty()) {
        lxb_dom_element_set_attribute(
            elem,
            reinterpret_cast<const lxb_char_t*>("class"), 5,
            as_lxb(classes), classes.size());
    }

    auto* elem_node = lxb_dom_interface_node(elem);
    lxb_dom_node_insert_child(parent, elem_node);
    parent_stack_.push_back(elem_node);
    cursor_stack_.push_back(nullptr);   // no old children to reconcile
    return elem;
}

void ImmRuntime::close_element() {
    if (parent_stack_.size() <= 1) return;
    // Tail-kill: anything left under the cursor for THIS element is
    // old content the view fn didn't visit on this render. Destroy it.
    destroy_from(cursor_stack_.back());
    parent_stack_.pop_back();
    cursor_stack_.pop_back();
}

void ImmRuntime::set_class(lxb_dom_element_t* el, std::string_view cls) {
    if (!el || cls.empty()) return;
    lxb_dom_element_set_attribute(
        el,
        as_lxb("class"), 5,
        as_lxb(cls), cls.size());
}

void ImmRuntime::set_attr(lxb_dom_element_t* el,
                          std::string_view name,
                          std::string_view value) {
    if (!el || name.empty()) return;
    lxb_dom_element_set_attribute(
        el,
        as_lxb(name), name.size(),
        as_lxb(value), value.size());
}

void ImmRuntime::append_text_to_current(std::string_view text) {
    if (parent_stack_.empty() || !doc_ || text.empty()) return;
    auto* parent = parent_stack_.back();
    auto& cursor = cursor_stack_.back();

    // Reuse path: cursor is already a text node. Compare and only
    // mutate when the content differs — that's the whole reason for
    // dumb-reconcile, no churn for unchanged text.
    if (cursor && cursor->type == LXB_DOM_NODE_TYPE_TEXT) {
        std::size_t old_len = 0;
        auto* old_data = lxb_dom_node_text_content(cursor, &old_len);
        const bool same = old_data && old_len == text.size() &&
            std::memcmp(old_data, text.data(), text.size()) == 0;
        if (!same) {
            lxb_dom_node_text_content_set(
                cursor, as_lxb(text), text.size());
        }
        cursor = cursor->next;
        return;
    }

    // Mismatch (cursor was an element, or no cursor at all): destroy
    // tail then append a fresh text node.
    destroy_from(cursor);
    cursor = nullptr;
    auto* tn = lxb_dom_document_create_text_node(
        lxb_dom_interface_document(doc_),
        as_lxb(text), text.size());
    if (!tn) return;
    lxb_dom_node_insert_child(parent, lxb_dom_interface_node(tn));
}

#endif  // AFFINEUI_STUB_BUILD

}  // namespace affineui::detail
