#!/usr/bin/env python3
"""
Generate and check a C++-compatible Lexbor source tree.

AffineUI ships source artifacts that are compiled by the host as C++.
Lexbor is normal C: it relies on implicit void* conversions, C compound
literals, C keywords that are C++ keywords, and generated C tables. This
tool keeps those packaging transforms out of the Lexbor fork by applying
them to a generated staging tree.

The generated tree is an intermediate distro input, not hand-edited source.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


PROXY_VOID_RETURN_FUNCTIONS = {
    "lexbor_array_get",
    "lexbor_array_obj_get",
    "lexbor_array_obj_last",
    "lexbor_array_obj_pop",
    "lexbor_array_obj_push",
    "lexbor_array_obj_push_n",
    "lexbor_array_obj_push_wo_cls",
    "lexbor_array_pop",
    "lexbor_bst_entry_data",
    "lexbor_calloc",
    "lexbor_dobject_alloc",
    "lexbor_dobject_by_absolute_position",
    "lexbor_dobject_calloc",
    "lexbor_dobject_free",
    "lexbor_free",
    "lexbor_hash_insert",
    "lexbor_hash_search",
    "lexbor_malloc",
    "lexbor_mem_alloc",
    "lexbor_mem_calloc",
    "lexbor_mraw_alloc",
    "lexbor_mraw_calloc",
    "lexbor_mraw_free",
    "lexbor_mraw_realloc",
    "lexbor_realloc",
}

CPP_COMPILE_FLAGS = [
    "-x", "c++",
    "-std=c++20",
    "-DLEXBOR_STATIC",
    "-Wno-c++11-narrowing",
    "-Wno-c99-designator",
    "-Wno-writable-strings",
    "-ferror-limit=0",
]

FUNCTION_DEF_RE = re.compile(
    r"(?m)^([A-Za-z_][\w\s\*]*?)\n([A-Za-z_][A-Za-z0-9_]*)\s*\([^;{}]*\)\s*\\?\s*\n\{"
)
FUNCTION_DECL_RE = re.compile(
    r"(?m)^(?:LXB_API\s+)?[A-Za-z_][\w\s\*]*?\n"
    r"((?:lexbor|lxb)_[A-Za-z0-9_]+)\s*\("
)
PUBLIC_NAME_RE = re.compile(r"\b(?:lexbor|lxb)_[A-Za-z0-9_]+\b")
PUBLIC_VAR_RE = re.compile(r"\b((?:lexbor|lxb)_[A-Za-z0-9_]+)\s*(?=\[|=|;)")
STATIC_SPLIT_FUNCTION_RE = re.compile(
    r"(?m)^static\b[^{;=]*?\n([A-Za-z_][A-Za-z0-9_]*)\s*\("
)
STATIC_LINE_SYMBOL_RE = re.compile(
    r"(?m)^static\b[^\n;({=]*\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?=\[|=|;|\()"
)


@dataclass
class CompileFailure:
    path: Path
    stderr: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def source_root(repo_root: Path) -> Path:
    return repo_root / "external" / "lexbor" / "source"


def copy_source_tree(src: Path, out: Path) -> Path:
    if not src.exists():
        raise FileNotFoundError(f"Lexbor source tree not found: {src}")
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(src, out)
    return out


def prefixed_name(prefix: str, name: str) -> str:
    return f"{prefix}{name}" if prefix else name


def write_cpp_compat_header(staged_source: Path, symbol_prefix: str) -> None:
    header = staged_source / "lexbor" / "core" / "cpp_compat.h"
    undef_header = staged_source / "lexbor" / "core" / "cpp_compat_undef.h"
    lines = [
        "/* Generated by AffineUI tools/lexbor_cpp_compat.py. */",
        "#ifdef __cplusplus",
        "#ifndef LEXBOR_CPP_COMPAT_TYPES_H",
        "#define LEXBOR_CPP_COMPAT_TYPES_H",
        "namespace lexbor_cpp_compat {",
        "struct ptr_proxy {",
        "    void *p;",
        "    template <class T> operator T *() const { return static_cast<T *>(p); }",
        "    template <class T> operator const T *() const { return static_cast<const T *>(p); }",
        "    operator void *() const { return p; }",
        "    operator const void *() const { return p; }",
        "};",
        "inline ptr_proxy ptr(void *p) { return {p}; }",
        "inline ptr_proxy ptr(const void *p) { return {const_cast<void *>(p)}; }",
        "}  // namespace lexbor_cpp_compat",
        "#endif  /* LEXBOR_CPP_COMPAT_TYPES_H */",
        "",
    ]

    for name in sorted(PROXY_VOID_RETURN_FUNCTIONS):
        macro_name = prefixed_name(symbol_prefix, name)
        lines.extend([
            f"#ifndef LXB_CPP_COMPAT_SKIP_{name}",
            f"#define {macro_name}(...) ::lexbor_cpp_compat::ptr(({macro_name})(__VA_ARGS__))",
            "#endif",
        ])

    lines.extend([
        "#endif  /* __cplusplus */",
        "",
    ])
    write_text(header, "\n".join(lines))

    lines = [
        "/* Generated by AffineUI tools/lexbor_cpp_compat.py. */",
    ]
    for name in sorted(PROXY_VOID_RETURN_FUNCTIONS):
        macro_name = prefixed_name(symbol_prefix, name)
        lines.extend([
            f"#ifdef {macro_name}",
            f"#undef {macro_name}",
            "#endif",
            f"#ifdef LXB_CPP_COMPAT_SKIP_{name}",
            f"#undef LXB_CPP_COMPAT_SKIP_{name}",
            "#endif",
        ])
    lines.extend([
        "#ifdef new",
        "#undef new",
        "#endif",
        "",
    ])
    write_text(undef_header, "\n".join(lines))


def collect_prefixed_symbols(staged_source: Path) -> list[str]:
    symbols: set[str] = set()

    for path in (staged_source / "lexbor").rglob("*.c"):
        text = read_text(path)
        for match in FUNCTION_DEF_RE.finditer(text):
            prefix = match.group(1)
            name = match.group(2)
            if "static" not in prefix.split() and PUBLIC_NAME_RE.fullmatch(name):
                symbols.add(name)

        for line in text.splitlines():
            stripped = line.strip()
            if (not stripped or stripped.startswith("static ")
                    or "(" in stripped or "=" not in stripped):
                continue
            match = PUBLIC_VAR_RE.search(stripped)
            if match is not None:
                symbols.add(match.group(1))

    for path in (staged_source / "lexbor").rglob("*.h"):
        text = read_text(path)
        symbols.update(FUNCTION_DECL_RE.findall(text))

        for line in text.splitlines():
            stripped = line.strip()
            if not (stripped.startswith("extern ")
                    or stripped.startswith("LXB_EXTERN ")):
                continue
            if "(" in stripped:
                continue
            match = PUBLIC_VAR_RE.search(stripped)
            if match is not None:
                symbols.add(match.group(1))

    return sorted(symbols)


def write_symbol_prefix_header(staged_source: Path, symbol_prefix: str) -> None:
    if not symbol_prefix:
        return

    symbols = collect_prefixed_symbols(staged_source)
    path = staged_source / "lexbor" / "core" / "symbol_prefix.h"
    lines = [
        "/* Generated by AffineUI tools/lexbor_cpp_compat.py. */",
        "#ifndef LEXBOR_SYMBOL_PREFIX_H",
        "#define LEXBOR_SYMBOL_PREFIX_H",
        "#define LEXBOR_AFFINEUI_SYMBOL_PREFIX 1",
        "",
    ]
    for name in symbols:
        lines.append(f"#define {name} {prefixed_name(symbol_prefix, name)}")
    lines.extend(["", "#endif  /* LEXBOR_SYMBOL_PREFIX_H */", ""])
    write_text(path, "\n".join(lines))

    def_h = staged_source / "lexbor" / "core" / "def.h"
    text = read_text(def_h)
    marker = "#define LEXBOR_DEF_H\n"
    include = marker + '\n#include "lexbor/core/symbol_prefix.h"\n'
    if "lexbor/core/symbol_prefix.h" not in text:
        text = text.replace(marker, include, 1)
    write_text(def_h, text)


def inject_base_helpers(staged_source: Path) -> None:
    path = staged_source / "lexbor" / "core" / "base.h"
    text = read_text(path)
    marker = "#define lexbor_min(val1, val2) ((val1) < (val2) ? (val1) : (val2))"
    helper = (
        marker + "\n\n"
        "#ifdef __cplusplus\n"
        "#define LEXBOR_CPP_STATIC_PTR(type, ...) "
        "([]() -> type * { static type v = __VA_ARGS__; return &v; }())\n"
        "#endif\n"
    )
    if "LEXBOR_CPP_STATIC_PTR" not in text:
        text = text.replace(marker, helper)
    write_text(path, text)


def patch_swar_endian_check(staged_source: Path) -> None:
    path = staged_source / "lexbor" / "core" / "swar.h"
    text = read_text(path)
    old = "#define LEXBOR_SWAR_IS_LITTLE_ENDIAN (*(unsigned char *) &(uint16_t){1})"
    new = (
        "#ifdef __cplusplus\n"
        "#define LEXBOR_SWAR_IS_LITTLE_ENDIAN (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)\n"
        "#else\n"
        "#define LEXBOR_SWAR_IS_LITTLE_ENDIAN (*(unsigned char *) &(uint16_t){1})\n"
        "#endif"
    )
    text = text.replace(old, new)
    write_text(path, text)


def replace_compound_pointer_literals(text: str) -> str:
    """Rewrite &(type) {...} to a C++ lambda-backed static object pointer."""
    out: list[str] = []
    i = 0
    n = len(text)

    while i < n:
        if not text.startswith("&(", i):
            out.append(text[i])
            i += 1
            continue

        j = i + 2
        paren_depth = 1
        while j < n and paren_depth:
            if text[j] == "(":
                paren_depth += 1
            elif text[j] == ")":
                paren_depth -= 1
            j += 1

        if paren_depth != 0:
            out.append(text[i])
            i += 1
            continue

        typ = text[i + 2:j - 1].strip()
        k = j
        while k < n and text[k].isspace():
            k += 1
        if k >= n or text[k] != "{":
            out.append(text[i])
            i += 1
            continue

        brace_depth = 0
        in_string = False
        escaped = False
        m = k
        while m < n:
            c = text[m]
            if in_string:
                if escaped:
                    escaped = False
                elif c == "\\":
                    escaped = True
                elif c == '"':
                    in_string = False
            else:
                if c == '"':
                    in_string = True
                elif c == "{":
                    brace_depth += 1
                elif c == "}":
                    brace_depth -= 1
                    if brace_depth == 0:
                        m += 1
                        break
            m += 1

        init = text[k:m]
        out.append(f"LEXBOR_CPP_STATIC_PTR({typ}, {init})")
        i = m

    return "".join(out)


def patch_generated_headers(staged_source: Path) -> None:
    for path in (staged_source / "lexbor").rglob("*.h"):
        text = replace_compound_pointer_literals(read_text(path))
        if path.as_posix().endswith("/lexbor/html/tokenizer/res.h"):
            text = re.sub(r"(\{0x[0-9A-Fa-f]+,\s*)(\")", r"\1(void *) \2", text)
        write_text(path, text)


def defined_function_names(text: str) -> set[str]:
    return {match.group(2) for match in FUNCTION_DEF_RE.finditer(text)}


def inject_cxx_file_prelude(path: Path) -> None:
    text = read_text(path)
    lines = text.splitlines()

    insert_at = 0
    for idx, line in enumerate(lines):
        if line.startswith("#include"):
            insert_at = idx + 1

    defined = defined_function_names(text)
    prelude = ["#define new lexbor_cpp_new"]
    for name in sorted(defined & PROXY_VOID_RETURN_FUNCTIONS):
        prelude.append(f"#define LXB_CPP_COMPAT_SKIP_{name} 1")
    prelude.append('#include "lexbor/core/cpp_compat.h"')

    lines[insert_at:insert_at] = prelude
    lines.append('#include "lexbor/core/cpp_compat_undef.h"')
    write_text(path, "\n".join(lines) + "\n")


def patch_c_translation_units(staged_source: Path) -> None:
    for path in (staged_source / "lexbor").rglob("*.c"):
        inject_cxx_file_prelude(path)


def apply_known_cxx_source_fixes(staged_source: Path) -> None:
    """Apply non-diagnostic fixes for C constructs that need structural edits."""
    path = staged_source / "lexbor" / "css" / "syntax" / "state.c"
    text = read_text(path)
    text = text.replace('static const lxb_char_t minuses[3] = "---";',
                        'static const lxb_char_t minuses[4] = "---";')
    text = text.replace('static const lxb_char_t minuses[2] = "--";',
                        'static const lxb_char_t minuses[3] = "--";')
    write_text(path, text)

    path = staged_source / "lexbor" / "html" / "tree.c"
    text = read_text(path)
    text = text.replace(
        "lxb_dom_character_data_t *chrs = NULL;\n"
        "    lxb_html_tree_insertion_position_t ipos;",
        "lxb_dom_character_data_t *chrs = NULL;\n"
        "    lxb_dom_node_t *text = NULL;\n"
        "    lxb_html_tree_insertion_position_t ipos;",
    )
    text = text.replace(
        "lxb_dom_node_t *text = lxb_html_tree_create_node(tree, LXB_TAG__TEXT,",
        "text = lxb_html_tree_create_node(tree, LXB_TAG__TEXT,",
    )
    write_text(path, text)

    path = staged_source / "lexbor" / "html" / "interfaces" / "element.c"
    text = read_text(path)
    text = text.replace(
        "walk->cb(walk->element, node->value, walk->ctx, style->sp, false)",
        "walk->cb(walk->element, (const lxb_css_rule_declaration_t *) node->value, "
        "walk->ctx, style->sp, false)",
    )
    text = text.replace(
        "walk->cb(walk->element, weak->value, walk->ctx,",
        "walk->cb(walk->element, (const lxb_css_rule_declaration_t *) weak->value, "
        "walk->ctx,",
    )
    write_text(path, text)

    path = staged_source / "lexbor" / "url" / "url.c"
    text = read_text(path)
    text = text.replace("opt |= (lxb_url_host_opt_t) LXB_URL_HOST_OPT_DECODE;",
                        "opt = (lxb_url_host_opt_t) (opt | LXB_URL_HOST_OPT_DECODE);")
    text = text.replace("opt |= (lxb_url_host_opt_t) LXB_URL_HOST_OPT_IDNA;",
                        "opt = (lxb_url_host_opt_t) (opt | LXB_URL_HOST_OPT_IDNA);")
    text = text.replace("*opt |= (lxb_url_host_opt_t) LXB_URL_HOST_OPT_IDNA;",
                        "*opt = (lxb_url_host_opt_t) (*opt | LXB_URL_HOST_OPT_IDNA);")
    write_text(path, text)


def prefix_file_static_symbols(staged_source: Path) -> None:
    for path in (staged_source / "lexbor").rglob("*.c"):
        text = read_text(path)
        names = set(STATIC_SPLIT_FUNCTION_RE.findall(text))
        names.update(STATIC_LINE_SYMBOL_RE.findall(text))

        if not names:
            continue

        rel = path.relative_to(staged_source).as_posix()
        digest = hashlib.sha1(rel.encode("utf-8")).hexdigest()[:10]
        for name in sorted(names, key=len, reverse=True):
            text = re.sub(rf"\b{re.escape(name)}\b",
                          f"aui_lexbor_static_{digest}_{name}", text)

        write_text(path, text)


def transform(staged_source: Path, symbol_prefix: str) -> None:
    write_symbol_prefix_header(staged_source, symbol_prefix)
    write_cpp_compat_header(staged_source, symbol_prefix)
    inject_base_helpers(staged_source)
    patch_swar_endian_check(staged_source)
    patch_generated_headers(staged_source)
    patch_c_translation_units(staged_source)
    apply_known_cxx_source_fixes(staged_source)
    prefix_file_static_symbols(staged_source)


def lexbor_c_sources(staged_source: Path, platform: str) -> list[Path]:
    paths = sorted((staged_source / "lexbor").rglob("*.c"))
    selected: list[Path] = []

    for path in paths:
        s = path.as_posix()
        if platform == "posix" and "/ports/windows_nt/" in s:
            continue
        if platform == "windows" and "/ports/posix/" in s:
            continue
        selected.append(path)

    return selected


def macos_sdk_flags() -> list[str]:
    if sys.platform != "darwin":
        return []

    result = subprocess.run(["xcrun", "--sdk", "macosx", "--show-sdk-path"],
                            text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    if result.returncode != 0:
        return []

    sdk = result.stdout.strip()
    return ["-isysroot", sdk] if sdk else []


def compile_source(cxx: str, cxx_flags: list[str], staged_source: Path,
                   obj_dir: Path, path: Path) -> CompileFailure | None:
    obj = obj_dir / (str(path.relative_to(staged_source)).replace("/", "__") + ".o")
    obj.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        cxx,
        *CPP_COMPILE_FLAGS,
        *cxx_flags,
        "-I", str(staged_source),
        "-c", str(path),
        "-o", str(obj),
    ]
    result = subprocess.run(cmd, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE)
    if result.returncode == 0:
        return None
    return CompileFailure(path=path, stderr=result.stderr)


def cast_type(raw: str) -> str:
    raw = raw.strip()
    if " (aka " in raw:
        raw = raw.split(" (aka ", 1)[0]
    return raw


def wrap_cast(typ: str, expr: str) -> str:
    expr = expr.strip()
    if expr.startswith(f"({typ})"):
        return expr
    return f"({typ}) ({expr})"


def prefix_rhs_cast(line: str, typ: str) -> tuple[str, bool]:
    idx = line.find("=")
    if idx < 0:
        return line, False
    if idx + 1 < len(line) and line[idx + 1] == "=":
        return line, False

    lhs = line[:idx + 1]
    rhs = line[idx + 1:].strip()
    if ";" not in rhs:
        casted = f"({typ}) {rhs}"
        if casted in line:
            return line, False
        return f"{lhs} {casted}", True

    suffix = ""
    if rhs.endswith(";"):
        rhs = rhs[:-1].rstrip()
        suffix = ";"
    casted = wrap_cast(typ, rhs)
    if casted in line:
        return line, False
    return f"{lhs} {casted}{suffix}", True


def prefix_return_cast(line: str, typ: str) -> tuple[str, bool]:
    match = re.search(r"\breturn\s+", line)
    if not match:
        return line, False

    expr = line[match.end():].strip()
    if ";" not in expr:
        return f"{line[:match.end()]}({typ}) {expr}", True

    suffix = ""
    if expr.endswith(";"):
        expr = expr[:-1].rstrip()
        suffix = ";"
    casted = wrap_cast(typ, expr)
    return f"{line[:match.end()]}{casted}{suffix}", True


def find_call_span(lines: list[str], line_idx: int, call_name: str) -> tuple[int, int, str] | None:
    text = ""
    start = line_idx

    for idx in range(line_idx, min(len(lines), line_idx + 24)):
        text += lines[idx] + "\n"
        if f"{call_name}(" not in text:
            continue

        open_idx = text.find(f"{call_name}(") + len(call_name)
        paren_depth = 0
        in_string = False
        escaped = False
        for c in text[open_idx:]:
            if in_string:
                if escaped:
                    escaped = False
                elif c == "\\":
                    escaped = True
                elif c == '"':
                    in_string = False
                continue

            if c == '"':
                in_string = True
            elif c == "(":
                paren_depth += 1
            elif c == ")":
                paren_depth -= 1
                if paren_depth == 0:
                    return start, idx, text

    return None


def split_args(args_text: str) -> list[str]:
    args: list[str] = []
    cur: list[str] = []
    paren = bracket = brace = 0
    in_string = False
    escaped = False

    for c in args_text:
        if in_string:
            cur.append(c)
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_string = False
            continue

        if c == '"':
            in_string = True
        elif c == "(":
            paren += 1
        elif c == ")":
            paren -= 1
        elif c == "[":
            bracket += 1
        elif c == "]":
            bracket -= 1
        elif c == "{":
            brace += 1
        elif c == "}":
            brace -= 1

        if c == "," and paren == 0 and bracket == 0 and brace == 0:
            args.append("".join(cur))
            cur = []
        else:
            cur.append(c)

    args.append("".join(cur))
    return args


def patch_call_argument(lines: list[str], line_no: int, call_name: str,
                        arg_no: int, typ: str) -> bool:
    span = find_call_span(lines, line_no - 1, call_name)
    if span is None:
        return False

    start, end, text = span
    call_pos = text.find(f"{call_name}(")
    open_idx = call_pos + len(call_name)

    paren_depth = 0
    close_idx = -1
    for idx, c in enumerate(text[open_idx:], start=open_idx):
        if c == "(":
            paren_depth += 1
        elif c == ")":
            paren_depth -= 1
            if paren_depth == 0:
                close_idx = idx
                break

    if close_idx < 0:
        return False

    before = text[:open_idx + 1]
    args = split_args(text[open_idx + 1:close_idx])
    after = text[close_idx:]

    idx = arg_no - 1
    if idx < 0 or idx >= len(args):
        return False

    arg = args[idx]
    leading = arg[:len(arg) - len(arg.lstrip())]
    new_arg = leading + wrap_cast(typ, arg.lstrip())
    if new_arg == arg:
        return False

    args[idx] = new_arg
    new_text = before + ",".join(args) + after
    lines[start:end + 1] = new_text.rstrip("\n").split("\n")
    return True


def apply_diagnostic_fixes(path: Path, stderr: str, symbol_prefix: str) -> bool:
    lines = read_text(path).splitlines()
    changed = False
    diag_lines = stderr.splitlines()
    i = 0

    while i < len(diag_lines):
        line = diag_lines[i]
        match = re.match(r"([^:]+):(\d+):(\d+): error: (.*)", line)
        if match is None:
            i += 1
            continue
        if Path(match.group(1)).resolve() != path.resolve():
            i += 1
            continue

        line_no = int(match.group(2))
        msg = match.group(4)

        type_match = re.search(r"assigning to '([^']+)'", msg)
        if type_match:
            typ = cast_type(type_match.group(1))
            new_line, did_change = prefix_rhs_cast(lines[line_no - 1], typ)
            if did_change:
                lines[line_no - 1] = new_line
                changed = True
            i += 1
            continue

        type_match = re.search(r"cannot initialize a variable of type '([^']+)'", msg)
        if type_match:
            typ = cast_type(type_match.group(1))
            new_line, did_change = prefix_rhs_cast(lines[line_no - 1], typ)
            if did_change:
                lines[line_no - 1] = new_line
                changed = True
            i += 1
            continue

        type_match = re.search(r"cannot initialize return object of type '([^']+)'", msg)
        if type_match:
            typ = cast_type(type_match.group(1))
            new_line, did_change = prefix_return_cast(lines[line_no - 1], typ)
            if did_change:
                lines[line_no - 1] = new_line
                changed = True
            i += 1
            continue

        call_match = re.search(r"no matching function for call to '([^']+)'", msg)
        if call_match:
            call_name = call_match.group(1)
            note_idx = i + 1
            while note_idx < len(diag_lines) and "candidate function not viable:" not in diag_lines[note_idx]:
                note_idx += 1
            if note_idx < len(diag_lines):
                note = diag_lines[note_idx]
                arg_match = re.search(
                    r"(?:to|from) '([^']+)'(?: \(aka '[^']+'\))? for "
                    r"(\d+)(?:st|nd|rd|th) argument",
                    note,
                )
                if arg_match:
                    typ = cast_type(arg_match.group(1))
                    arg_no = int(arg_match.group(2))
                    call_names = [call_name]
                    if symbol_prefix and call_name.startswith(symbol_prefix):
                        call_names.append(call_name[len(symbol_prefix):])
                    for candidate_name in call_names:
                        if patch_call_argument(lines, line_no, candidate_name,
                                               arg_no, typ):
                            changed = True
                            break
            i += 1
            continue

        i += 1

    if changed:
        if path.as_posix().endswith("/lexbor/url/url.c"):
            text = "\n".join(lines)
            text = re.sub(
                r"(\s*)(\*?opt)\s*\|=\s*\(lxb_url_host_opt_t\)\s*\((LXB_URL_HOST_OPT_[A-Z_]+)\);",
                r"\1\2 = (lxb_url_host_opt_t) (\2 | \3);",
                text,
            )
            lines = text.splitlines()
        write_text(path, "\n".join(lines) + "\n")
    return changed


def repair_with_compiler(cxx: str, cxx_flags: list[str], staged_source: Path,
                         obj_dir: Path, platform: str, symbol_prefix: str,
                         max_rounds: int) -> list[CompileFailure]:
    sources = lexbor_c_sources(staged_source, platform)
    failures: list[CompileFailure] = []

    for round_idx in range(max_rounds):
        failures = []
        changed = 0

        for path in sources:
            failure = compile_source(cxx, cxx_flags, staged_source, obj_dir, path)
            if failure is None:
                continue
            failures.append(failure)
            if apply_diagnostic_fixes(path, failure.stderr, symbol_prefix):
                changed += 1

        if not failures or changed == 0:
            return failures

        print(f"repair round {round_idx + 1}: {len(failures)} failing files, "
              f"patched {changed}", file=sys.stderr)

    return failures


def check_compiles(cxx: str, cxx_flags: list[str], staged_source: Path, obj_dir: Path,
                   platform: str) -> list[CompileFailure]:
    failures: list[CompileFailure] = []
    for path in lexbor_c_sources(staged_source, platform):
        failure = compile_source(cxx, cxx_flags, staged_source, obj_dir, path)
        if failure is not None:
            failures.append(failure)
    return failures


def unprefixed_global_symbols(obj_dir: Path) -> list[str]:
    nm = shutil.which("nm")
    if nm is None:
        return []

    offenders: list[str] = []
    pattern = re.compile(r"\b_?(?:lexbor|lxb)_[A-Za-z0-9_]+\b")
    for obj in sorted(obj_dir.rglob("*.o")):
        result = subprocess.run([nm, "-g", str(obj)], text=True,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
        if result.returncode not in (0, 1):
            continue
        for line in result.stdout.splitlines():
            if pattern.search(line):
                offenders.append(line.strip())

    return offenders


def default_platform() -> str:
    return "windows" if os.name == "nt" else "posix"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--root", default=".", help="AffineUI repo root")
    parser.add_argument("--out", required=True, help="generated output directory")
    parser.add_argument("--platform", choices=("posix", "windows", "all"),
                        default=default_platform(),
                        help="port sources to compile during --check")
    parser.add_argument("--check", action="store_true",
                        help="compile generated Lexbor C files as C++")
    parser.add_argument("--no-repair", action="store_true",
                        help="skip compiler-guided cast repair")
    parser.add_argument("--cxx", default=os.environ.get("CXX", "clang++"),
                        help="C++ compiler for --check")
    parser.add_argument("--symbol-prefix", default="aui_",
                        help="prefix for generated Lexbor linker symbols")
    parser.add_argument("--no-symbol-prefix", action="store_true",
                        help="leave Lexbor linker symbols unchanged")
    parser.add_argument("--max-repair-rounds", type=int, default=8)
    args = parser.parse_args()

    repo_root = Path(args.root).resolve()
    out = Path(args.out).resolve()
    staged_source = copy_source_tree(source_root(repo_root), out / "source")
    symbol_prefix = "" if args.no_symbol_prefix else args.symbol_prefix

    transform(staged_source, symbol_prefix)

    print(f"wrote {staged_source}")

    if not args.check:
        return 0

    obj_dir = out / "obj"
    if obj_dir.exists():
        shutil.rmtree(obj_dir)
    obj_dir.mkdir(parents=True)

    cxx_flags = macos_sdk_flags()

    if args.no_repair:
        failures = check_compiles(args.cxx, cxx_flags, staged_source, obj_dir,
                                  args.platform)
    else:
        failures = repair_with_compiler(args.cxx, cxx_flags, staged_source, obj_dir,
                                        args.platform, symbol_prefix,
                                        args.max_repair_rounds)
        if not failures:
            failures = check_compiles(args.cxx, cxx_flags, staged_source, obj_dir,
                                      args.platform)

    if failures:
        print(f"lexbor-cpp: {len(failures)} files failed", file=sys.stderr)
        for failure in failures[:8]:
            rel = failure.path.relative_to(staged_source)
            print(f"\n--- {rel}", file=sys.stderr)
            print("\n".join(failure.stderr.splitlines()[:80]), file=sys.stderr)
        return 1

    if symbol_prefix:
        offenders = unprefixed_global_symbols(obj_dir)
        if offenders:
            print("lexbor-cpp: unprefixed Lexbor globals remain", file=sys.stderr)
            for line in offenders[:20]:
                print(line, file=sys.stderr)
            return 1

    count = len(lexbor_c_sources(staged_source, args.platform))
    print(f"compiled {count} Lexbor C files as C++")
    if symbol_prefix:
        print(f"prefixed Lexbor globals with {symbol_prefix}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
